services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEBOT_API_TOKEN
      sync: false
      - key: BOT_LINK
      sync: false
      - key: CHANNEL_ID
